### ISSUE TITLE
No such model: code-davinci-002

### ISSUE THREAD

**Issue by kwanUm** [tom-doerr/zsh_codex#16]
I'm getting the error in title. org_id & secret_key are correct, but I still get the error immediately after pressing ^X.

Anyone else experiences that?

**Comment by kwanUm** [comment]
Traceback (most recent call last):                                                                            
  File "/private/home/orik/.oh-my-zsh/custom/plugins/zsh_codex/create_completion.py", line 64, in <module>
    response = openai.Completion.create(engine='code-davinci-002', prompt=prompt_prefix, suffix=prompt_suffix, temperature=0.5, max_tokens=50, stream=STREAM)
  File "/private/home/orik/.conda/envs/design5_py38/lib/python3.8/site-packages/openai/api_resources/completion.py", line 31, in create
    return super().create(*args, **kwargs)
  File "/private/home/orik/.conda/envs/design5_py38/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 100, in create
    response, _, api_key = requestor.request(
  File "/private/home/orik/.conda/envs/design5_py38/lib/python3.8/site-packages/openai/api_requestor.py", line 120, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/private/home/orik/.conda/envs/design5_py38/lib/python3.8/site-packages/openai/api_requestor.py", line 327, in _interpret_response
    self._interpret_response_line(
  File "/private/home/orik/.conda/envs/design5_py38/lib/python3.8/site-packages/openai/api_requestor.py", line 360, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: No such model: code-davinci-002

**Comment by tom-doerr** [comment]
Do you have access to Codex? Having access to the OpenAI API is not enough.
More Info:
https://github.com/tom-doerr/zsh_codex/issues/15
https://github.com/tom-doerr/zsh_codex/issues/13

**Comment by tupacalypse187** [comment]
I know this is an old issue, but I see this happening for me. I have a paid codex account setup but get the below error. Has the model changed and needs to be adjusted or is this an issue on my end? Thanks.

I'm using Hyper.js with Fig and zsh. Thank you.

```
# show the number of files in the current directoryTraceback (most recent call last):
  File "/Users/cyantorno/.oh-my-zsh/custom/plugins/zsh_codex/create_completion.py", line 64, in <module>
    response = openai.Completion.create(engine='code-davinci-002', prompt=prompt_prefix, suffix=prompt_suffix, temperature=0.5, max_tokens=50, stream=STREAM)
  File "/Users/cyantorno/Library/Python/3.9/lib/python/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/cyantorno/Library/Python/3.9/lib/python/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/cyantorno/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/cyantorno/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/cyantorno/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `code-davinci-002` does not exist
```
