### ISSUE TITLE
No such organization: Personal.

### ISSUE THREAD

**Issue by tomc98** [tom-doerr/zsh_codex#5]
When trying to run I get:

` echo Traceback (most recent call last):
  File "/home/tc/.oh-my-zsh/custom/plugins/zsh_codex/create_completion.py", line 67, in <module>
    response = openai.Completion.create(engine='davinci-codex', prompt=input_prompt, temperature=0.5, max_tokens=32, stream=STREAM)
  File "/home/tc/.local/lib/python3.9/site-packages/openai/api_resources/completion.py", line 31, in create
    return super().create(*args, **kwargs)
  File "/home/tc/.local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 66, in create
    response, _, api_key = requestor.request(
  File "/home/tc/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 129, in request
    resp = self.interpret_response(rbody, rcode, rheaders, stream=stream)
  File "/home/tc/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 348, in interpret_response
    return self.interpret_response_line(rbody, rcode, rheaders, stream)
  File "/home/tc/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 367, in interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: No such organization: Personal.
`

**Comment by tom-doerr** [comment]
In the `openaiapirc` you need to set the `organization_id` to the id that OpenAI gives you, you can't just set it to "Personal".

**Comment by demipixel** [comment]
To answer the what the question probably was, you can find it here:

https://beta.openai.com/account/org-settings
